stage:
  test:
    env:
      image: 'aone-base-global/alios7-nodejs-ci:1.0.0'
    plugin:
      -
        param:
          url: '${repo}'
          branch: '${branch}'
          path: '${source_root}'
          isDelGit: 'false'
        name: checkout
        pos: front
      -
        param:
          version: node-8
          source: '${source_root}'
        name: node_envs
        pos: front
    exec:
      - 'export PATH=$PWD/node_modules/.bin:$HOME/.cli:$PATH'
      - 'echo $PATH'
      - 'wget https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_v1.12.13+hotfix.5-stable.tar.xz'
      - 'tar xvf ./flutter_linux_v1.12.13+hotfix.5-stable.tar.xz'
      - 'export PATH="$PATH:`pwd`/flutter/bin"'
      - 'tnpm run ci'
pipeline:
  - 'test'
