stage:
  test:
    env:
      image: 'alpha/flutter-engine:latest'
    plugin:
      -
        param:
          url: '${repo}'
          branch: '${branch}'
          path: '${source_root}'
          isDelGit: 'false'
        name: checkout
        pos: front
    exec:
      - 'echo $PATH'
      - 'cd dartfm && dartanalyzer --options analysis_options.yaml .'
pipeline:
  - 'test'
