name: sdk
description: Kraken embed SDK
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  kraken:
    path: ../kraken

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  module:
    androidX: true
    androidPackage: com.taobao.kraken
    iosBundleIdentifier: com.taobao.kraken
