name: kraken
description: Kraken Dart Framework
version: 0.2.0
author: Kranken Team

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  ffi: ^0.1.3-dev.3
  path: ^1.6.4
  requests: ^3.0.1
  flutter:
    sdk: flutter
  meta: ^1.1.6
  kraken_video_player:
    path: ../plugins/kraken_video_player

dev_dependencies:
  flutter_test:
    sdk: flutter

