name: Integration Test WorkFlow

on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  integration_test:
    runs-on: self-hosted
    steps:
    - name: Set branch name
      run: echo >>$GITHUB_ENV BRANCH_NAME=${GITHUB_REF#refs/heads/}
    - name: Echo branch name
      run: echo ${BRANCH_NAME}
    - name: Clone The Code
      run: "\n
if [ -d "${RUNNER_WORKSPACE}/kraken_${BRANCH_NAME}" ]; then
  git clone -b ${BRANCH_NAME} git@github.com:openkraken/kraken.git --depth=1 ${RUNNER_WORKSPACE}/kraken_${BRANCH_NAME}
elif
  cd ${RUNNER_WORKSPACE}/kraken_${BRANCH_NAME}
  git pull
fi"
    - name: Run Test
      run: cd ${RUNNER_WORKSPACE}/kraken_${BRANCH_NAME} && npm test

