name: Integration Test WorkFlow

on: [push, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  integration_test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Run Test
      run: npm test
  upload_snapshots:
    runs-on: self-hosted
    if: ${{ always() }}
    needs: integration_test
    steps:
    - name: Upload Snapshots
      run: node scripts/upload_snapshots.js
