name: Sync main code to release branch

on: [workflow_dispatch, push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  flutter_2_2_x:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'release/flutter-2.2.x'
    - name: Opening pull request
      uses: tretuna/sync-branches@1.2.0
      with:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        FROM_BRANCH: 'main'
        TO_BRANCH: 'release/flutter-2.2.x'
