name: kraken
description: Kraken Dart Framework
version: 0.3.0
author: Kraken Team
homepage: http://rax.alibaba-inc.com/kraken

environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: ">=1.15.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  archive: ^ 2.0.13
  path: ^1.6.4
  requests: ^3.0.1
  meta: ^1.1.6
  flare_flutter: ^2.0.1
  ffi: ^0.1.3
  mqtt_client: ^6.0.0
  connectivity: ^0.4.8
  shared_preferences: ^0.5.6
  device_info: ^0.4.1 # Only support iOS and Android.
  kraken_video_player: ^0.1.0
  kraken_camera: ^0.1.0
  kraken_webview: ^0.1.0
  kraken_audioplayers: ^0.1.0
  kraken_geolocation: ^0.1.0
  path_provider: ^1.1.0
  dio: ^2.0.2
  vector_math: ^ 2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
