name: kraken
description: Kraken Dart Framework
version: 0.2.0
author: Kraken Team

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  path: ^1.6.4
  requests: ^3.0.1
  flutter:
    sdk: flutter
  meta: ^1.1.6
  flare_flutter: ^2.0.1
  ffi: ^0.1.3
  connectivity: ^0.4.8
  shared_preferences: ^0.5.6
  device_info: ^0.4.1 # Only support iOS and Android.
  kraken_video_player:
    path: ../plugins/kraken_video_player
  kraken_webview:
    path: ../plugins/kraken_webview
  audioplayers:
    path: ../plugins/audioplayers
  location:
    path: ../plugins/geolocation

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: AlibabaPuHuiTi
      fonts:
        - asset: fonts/Alibaba-PuHuiTi-Regular.ttf
        - asset: fonts/Alibaba-PuHuiTi-Light.ttf
          weight: 300
        - asset: fonts/Alibaba-PuHuiTi-Medium.ttf
          weight: 500
        - asset: fonts/Alibaba-PuHuiTi-Bold.ttf
          weight: 700
        - asset: fonts/Alibaba-PuHuiTi-Heavy.ttf
          weight: 900
    - family: AlibabaSans
      fonts:
        - asset: fonts/AlibabaSans-Regular.otf
        - asset: fonts/AlibabaSans-Italic.otf
          style: italic
        - asset: fonts/AlibabaSans-Light.otf
          weight: 300
        - asset: fonts/AlibabaSans-LightItalic.otf
          weight: 300
          style: italic
        - asset: fonts/AlibabaSans-Medium.otf
          weight: 500
        - asset: fonts/AlibabaSans-MediumItalic.otf
          weight: 500
          style: italic
        - asset: fonts/AlibabaSans-Bold.otf
          weight: 700
        - asset: fonts/AlibabaSans-BoldItalic.otf
          weight: 700
          style: italic
        - asset: fonts/AlibabaSans-Heavy.otf
          weight: 900
        - asset: fonts/AlibabaSans-HeavyItalic.otf
          weight: 900
          style: italic
    - family: AlibabaSans-Black
      fonts:
        - asset: fonts/AlibabaSans-Black.otf
