name: kraken
description: Kraken Dart Framework
version: 0.2.0
author: Kraken Team

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  path: ^1.6.4
  requests: ^3.0.1
  flutter:
    sdk: flutter
  meta: ^1.1.6
  flare_flutter: ^2.0.1
  ffi: ^0.1.3
  connectivity: ^0.4.6
  connectivity_macos: ^0.0.1
  device_info: ^0.4.1 # Only support iOS and Android.
  kraken_video_player:
    path: ../plugins/kraken_video_player

dev_dependencies:
  flutter_test:
    sdk: flutter

