name: kraken
description: Kraken Framework
version: 0.3.1+0
homepage: http://rax.alibaba-inc.com/kraken

environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: ">=1.15.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  archive: ^2.0.11
  path: ^1.6.4
  meta: ^1.1.6
  flare_flutter: ^2.0.1
  ffi: ^0.1.3
  mqtt_client: ^6.0.0
  connectivity: ^0.4.8
  web_socket_channel: ^1.1.0
  shared_preferences: ^0.5.6
  device_info: ^0.4.1 # Only support iOS and Android.
  path_provider: ^1.1.0
  dio: ^3.0.9
  web_socket_channel: ^1.1.0
  vector_math: ^ 2.0.8
  kraken_video_player:
    path: ../plugins/kraken_video_player
  kraken_camera:
    path: ../plugins/kraken_camera
  kraken_webview:
    path: ../plugins/kraken_webview
  kraken_audioplayers:
    path: ../plugins/kraken_audioplayers
  kraken_geolocation:
    path: ../plugins/kraken_geolocation

dev_dependencies:
  effective_dart: ^1.2.1
  flutter_test:
    sdk: flutter

flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  #
  # NOTE: This new plugin description format is not supported on Flutter's
  # stable channel as of 1.9.1. A plugin published using this format will not
  # work for most clients until the next major stable release.
  # However, it is required in order to declare macOS support.
  plugin:
    platforms:
      android:
        package: com.taobao.kraken
        pluginClass: KrakenSDKPlugin
      ios:
        pluginClass: KrakenSDKPlugin
      macos:
        pluginClass: KrakenSDKPlugin
